### ISSUE TITLE
LEIA - organização scrum para sequuência de trabalho da equipe

### ISSUE THREAD

**Issue by Psykozis** [YbysyS/YbysyS#3]
Ontem, diante da reunião definimos algumas questões

Nossa gaveta de ideias possui as seguintes ideias úteis
- classificador de grãos por imagens
- este lado para cima
- Como deixar de ser um merda
- melhoramento genético
- sistema de verificação e calculo de sistemas solares
- analisador de thd
 
**- Guarda chuva ybysys**
-- sistema ybysys para monitoramento de fenomenos 
-- alemometro
-- estufa de uBiomas
-- sensor de umidade
-- sensor de composto
-- isobus wifi
-- lora

Decidimos por focar no guarda-chuva ybysys, em especial os sensores de umidade e composto que podem nos dar retorno mais rápido.
Decidimos por conta do dolar dar sequência no projeto de 'melhoramento genético'

Foi decidido que por enquanto serei o scrum master... significa que terei de cobrar as sequencias planejadas afim de que tenhamos resultados dentro dos tempos planejados, o scrum original fala em reuniões diarias e mensais, acho que devido nossas vidas fica dificil ser diário, mas semanalmente seria legal fazer essas reuniões.

Abaixo seguem algumas  que encontrei para trabalhar com a organização scrum dentro do git
Scrum no github
-itens são reportados como issues
-------assim que o novo issue é criado, coloque labels ou um agrupamento em 'milestones' (ponto ou evento importante) 
-------issues permitem conversação sobre AQUELE ITEM, e possibilita-se criar listas de tarefas para que tenhamos marcadores de progresso. 
-Pontos e meta datas são assinados como labels nos itens
-------     prioridade(lowest, low, medium, high, highest) ->  priority: lowest 
-------     pontos (número) -> point: 1
-------     tipos () -> exemplos
    type: bug: bug
    type:chore: chore, maintenance work
    type:feature: new feature
    type:infrastructure: infrastructure related
    type:performance: performance related
    type:refactor: refactor
    type:test: test related

-milestones são, nesse caso, usados para agrupar issues em sprints

**Comment by Psykozis** [comment]
dentre esta lista de projetos, 

Selecionamos os com retorno a curto prazo mais prováveis
Decidimos por não perder o guarda chuva ybysys, e que o mais próximo de um fim é o sensor de umidade para solos/sensor de compostos que é basicamente o mesmo sensor

foi decidido que devemos começar a fazer a patente o quanto antes (pois não depende de nenhum outro passo)
Foi decidido involuntariamente pelo dolar baixar para mandar vir as placas e fazer validações.
Foi decidio que assim que chegar faremos as analizes novamente e estudos para a viabilidade de verificação de macro nutrientes.

**Comment by Psykozis** [comment]
além disto, 
como os demais projetos possuem limitantes em hw parecidos com a placa, ou ainda, pouca probabilidade de retorno financeiro ou retorno desconhecido pelo nicho de mercado.

O projeto 'melhoramento genético' possui a maior probabilidade de sequência sem investimentos grandes e com possibilidade de retorno a curto prazo.

--- precisamos decidir em continuar o legado do programa utilizado até então f90, e ficarmos engessados em tal formato, ou se vamos fazer do zero, mas com total possibilidade de fazermos além ou termos outras análizes que tal programa não comporta, por exemplo recomendações de cruzas, ajudando a diminuir indices de cosanguinidade.
--- que será um software de auxilio a especialistas da área ou de apoio ao manejo para quem precisa, mas sempre necessitando do auxilio de um proficional (para não cairmos em questões de ética animal e bem estar)
--- foi decidido que o programa f90 será utilizado como golden model

 foi decidido que necessariamente precisamos do Zoologo Daniel, pois este conhece as técnicas e trabalha com isto, além de ter nos procurado para fazer esta parceria.
--- precisamos que ele explique tais matrizes

Como será utilizado por pessoas sem entendimento, agronomos e zoologos que são meio leigos em tecnologias o design conta muito para que seja uma ideia de sucesso, e a forma de visualização, coisas que nós nunca nos importamos muito, é chave para isto. para isto discutimos, que seria interessante chamar algum designer.
foi exposto que eu tenho um dindo, que é designer e que trabalha com linhas de carnesfrigoríficos, abatedouros e criadores de determinados setores, talvez seja interessante chamar ele no final, e ver alguma forma de pagamento por comissão (exposto pelos guris na reunião), onde ele faça a analize das personas, faça o melhor estudo da parte visual, e use o próprio networking dele para que nossa ideia exploda em níveis maiores. Coisa que eu não acho ser dificil que ele faça, já que tem uma cooperativa de design com minha irmã e mais um maluco e fazem algumas coisas por nome tbm. que tendam a ter retorno.

**Comment by Psykozis** [comment]
para este ultimo, foi decidido que devemos primeiro marcar uma reunião como Daniel

**Comment by enjoycowboy** [comment]
Resumido no README. Arquivando...
